#!/usr/bin/env bash
# Configures an Ubuntu server with specific IP resolutions
sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts > /tmp/hosts_tmp
echo "8.8.8.8 facebook.com" >> /tmp/hosts_tmp
cat /tmp/hosts_tmp > /etc/hosts

